### ISSUE TITLE
Different sys.argv behavour

### ISSUE THREAD

**Issue by techhazard** [tusharsadhwani/zxpy#10]
### Problem description
When I run a zxpy script, the behaviour of `sys.argv` is not the same as regular python.

#### Setup
I ran `poetry init` in an empy directory, and used `poetry add zxpy` to install `zxpy` (version `1.2.4`).

#### `python3`

I have the following script (`test_python.py`):
```
#!/usr/bin/env python3
import sys
print(sys.argv)
```
If I run the script as `poetry run python3 ./test_python.py`, the output is:
```
['./test_python.py']
```
If I then run `chmod +x ./test_python.py && poetry run ./test_python.py`, the output is:
```
['./test_python.py']
```

#### `zxpy`

I have the following script (`test_zxpy.py`):
```
#!/usr/bin/env zxpy
import sys
print(sys.argv)
```
If I run the script as `poetry run zxpy ./test_zxpy.py`, the output is:
```
['/home/techhazard/.cache/pypoetry/virtualenvs/aoeuaoe-BGFxEDCR-py3.9/bin/zxpy', 'test_zxpy.py']
```
If I then run `chmod +x ./test_zxpy.py && poetry run ./test_zxpy.py`, the output is:

```
['/home/techhazard/.cache/pypoetry/virtualenvs/aoeuaoe-BGFxEDCR-py3.9/bin/zxpy', 'test_zxpy.py']
```

### Expected behaviour:

When `zxpy` is run, the `sys.argv` values should not include the `zxpy` executable.

**Comment by tusharsadhwani** [comment]
Hey, thanks for the issue! I totally forgot about `argv`.

Fortunately, this should be an easy fix.

**Comment by tusharsadhwani** [comment]
Do confirm if `pip install zxpy==1.2.5` fixes the issue for you.

**Comment by techhazard** [comment]
Thanks for the quick fix!
