### ISSUE TITLE
NameError: name 'run_shell' is not defined

### ISSUE THREAD

**Issue by manfredlotz** [tusharsadhwani/zxpy#19]
Sorry for being a pain in the neck. 

But, now using 1.4.2 it seems something else is broken

Running `examples/script.py` I get

```
Traceback (most recent call last):
  File "/home/manfred/.local/bin/zxpy", line 8, in <module>
    sys.exit(cli())
  File "/home/manfred/.local/lib/python3.8/site-packages/zx.py", line 56, in cli
    run_zxpy(filename, module)
  File "/home/manfred/.local/lib/python3.8/site-packages/zx.py", line 121, in run_zxpy
    exec(code, {'__name__': '__main__'})
  File "./y.py", line 2, in <module>
    ~'echo Hello world!'
NameError: name 'run_shell' is not defined
```

**Comment by jack1142** [comment]
Sorry, that's my bad - I didn't realize that the transformed code is using functions defined *in* zxpy. The easy solution here is to just put the used utility functions in the globals. This is prone to the user replacing it with some of their own functions with the same names but from what I can tell this was already the case *before* the change in 1.4.1 was made.

This might need a more clever solution in the future but it's probably good enough for now?

**Comment by manfredlotz** [comment]
Just to mention it: If I assign `~'mycmd...` to something then I get `NameError: name 'run_shell_alternate' is not defined`

**Comment by tusharsadhwani** [comment]
Yeah I should've ran the test cases before committing that last one. I should set up pre-commit on this repository :P

Anyways, I'll create a new patch tomorrow morning, which is ~ 9 hours from now.

**Comment by tusharsadhwani** [comment]
@manfredlotz 1.4.3 is up
@jack1142 thanks for the quick patch :)

**Comment by tusharsadhwani** [comment]
> Sorry for being a pain in the neck.

Making me realise I pushed a broken version isn't being a pain in the neck, thanks for that :D

**Comment by manfredlotz** [comment]
Things looking good now. Thanks a lot!
