### ISSUE TITLE
~ commands not working in a for loop

### ISSUE THREAD

**Issue by manfredlotz** [tusharsadhwani/zxpy#21]
The following example
```
#!/usr/bin/env zxpy

def main():
    ~'/bin/echo "This works fine"'
    for u in [1, 2]:
        print(u)
        ~'/bin/echo "Not working"'

if __name__ == '__main__':
    main()
```

gives as output only:

```
This works fine
1
2
```

**Comment by tusharsadhwani** [comment]
Alright I'll take a look

**Comment by tusharsadhwani** [comment]
Okay, I've figured the issue. Should probably be simple to fix

**Comment by tusharsadhwani** [comment]
Fixed in 1.4.4, do test!

**Comment by tusharsadhwani** [comment]
BTW, every release - all the way back - has patch notes mentioning what was fixed.
Like the current one: https://github.com/tusharsadhwani/zxpy/releases/tag/1.4.4

**Comment by manfredlotz** [comment]
I tested it. Looks good now. Thanks a lot.
