### ISSUE TITLE
pipes is deprecated for python 3.13

### ISSUE THREAD

**Issue by thewchan** [tusharsadhwani/zxpy#56]
See: https://docs.python.org/3/library/pipes.html; therefore `zxpy` is not compatible with python >= 3.13

**Comment by tusharsadhwani** [comment]
zxpy 1.6.4 has been released, and it no longer uses the `pipes` module. Thanks for pointing this out! Feel free to test and close the issue.

**Comment by thewchan** [comment]
Thanks so much @tusharsadhwani, works like a charm now!
