### ISSUE TITLE
How to deal with return codes

### ISSUE THREAD

**Issue by manfredlotz** [tusharsadhwani/zxpy#6]
Perhaps I miss something easy. 

But I could not see how I would deal with return codes > 0, i.e a command I issue returns an error.  Example: `~'cat /etc/shadow`

**Comment by tusharsadhwani** [comment]
You could do something like:

```
return_code = ~'cat /etc/shadow &> /dev/null; echo $?'
print(return_code)  # 1
```

Bash itself has support for a bunch of these redirect requirements. Although not the cleanest, this should work for such cases.

**Comment by tusharsadhwani** [comment]
I could possibly change the syntax of the return btw:

`output, stderr_output, return_code = ~'...'`

You would be able to get each one of the values by using 1, 2 or 3 values on the left hand side respectively.
Does this syntax seem worth adding?

**Comment by manfredlotz** [comment]
Thanks for your quick answer.I think it would be great to have stdout, stderr and return code which would give maximum flexibility.

**Comment by tusharsadhwani** [comment]
```pycon
zxpy shell
Python 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0]

>>> *_, return_code = ~'cat /etc/shadow'
>>> return_code
1
>>>
```

Latest behaviour in v1.3.0

If there's any other issues, feel free to re-open.

**Comment by manfredlotz** [comment]
I did some tests and things looking good. There is only one observation I made.

I think it would be good to return None instead of an empty string if there is nothing in stdout resp. stderr.

Thanks a lot for your work.

**Comment by tusharsadhwani** [comment]
@manfredlotz I'm just forwarding what the `subprocess` standard library returns.

Also I think empty string is better because you can always be sure that it's gonna be of type `str`, so you can reliable do things like `stdout.split()` or `stdout.partition(':')` etc., without needing to check for `None` first.

**Comment by manfredlotz** [comment]
Your argument makes sense. Agree.
